version: "3.9" # optional since v1.27.0
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRESS_PASSWORD: secret
      POSTGRESS_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "5432:5432"
  hw06:
    build: .
    container_name: hw06_orm
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
